### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by tbergen1** [mervanamerbabe/DasmotosProject#3]
Overall, you did a good job with this project,  Your formatting was pretty good.  You also showed good knowledge of HTML by choosing the appropriate semantic elements.  I would recommend going back through and cleaning up your CSS a bit to leverage inheritance fully.  I would also recommend adding comments to your code.  Other than that, great work!

**Comment by mervanamerbabe** [comment]
Great, I haven't gotten into the habit of adding comments and will work now to improve that in my code. Thank you!
